
package com.fytc.AnalizadorLexico.utils;


public enum Tokens {
    InicioAlgoritmo,
    FinAlgoritmo,
    Encadenar,
    PuntoYComa,
    DosPuntos,
    AbreParentesis,
    CierreParentesis,
    Comilla,
    TipoDeDatoCaracter,
    TipoDeDatoEntero,
    TipoDeDatoLogico,
    TipoDeDatoReal,
    Igual,
    Suma,
    Resta,
    Multiplicacion,
    Division,
    Potenciacion,
    Identificador,
    Numero,
    ERROR,
    Mayor,
    Menor,
    MenorOIgual,
    MayorOIgual,
    Distinto,
    Conjuncion,
    Disyuncion,
    Negacion,
    Modulo,
    RaizCuadrada,
    ValorAbsoluto,
    LogaritmoNatural,
    FuncionExponencial,
    Seno,
    Coseno,
    Tangente,
    Arcoseno,
    Arcocoseno,
    Arcotangente,
    ParteEntera,
    EnteroMasCercano,
    EnteroAleatorio,
    Longitud,
    ConcatenarCadenas,
    ConvertirVariableANumero,
    ConvertirVariableATexto,
    EntradaLectura,
    SalidaEscritura,
    Asignacion,
    InicioCondicionalSi,
    EntoncesIntrucciones,
    CondicionalSi,
    FinCondicionalSi,
    InicioRepeticionMientras,
    HacerIntrucciones,
    FinRepeticionMientras,
    InicioPara,
    MarcarDesde,
    MarcarConPaso,
    FinPara,
    DefinirVariable,
    DefinirComoTipo,
    DefinirDimension,
    InicioProceso,
    FinProceso,
    InicioSubProceso,
    ComenzarSubProceso,
    FinSubProceso,


}
